import type { Metadata } from "next";
import { Dancing_Script, Inter, Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["100","200","300","400", "500", "600", "700", "800", "900"] });
const dancing_script = Dancing_Script({ subsets: ["latin"], weight: ["400","500", "600", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dancing_script.className} flex flex-col h-screen relative`}>{children}</body>
    </html>
  );
}
